/**
 * App Redux Action Types
 */
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

// Cat Breeds Actions
export const GET_CAT_BREEDS = 'GET_CAT_BREEDS';
export const GET_CAT_BREEDS_SUCCESS = 'GET_CAT_BREEDS_SUCCESS';
export const GET_CAT_BREEDS_FAILURE = 'GET_CAT_BREEDS_FAILURE';

// Cats Actions
export const GET_CATS = 'GET_CATS';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILURE = 'GET_CATS_FAILURE';
export const SET_CATS_FILTER = 'SET_CATS_FILTER';
export const SET_SELECTED_CAT = 'SET_SELECTED_CAT';
export const SET_SELECTED_CAT_SUCCESS = 'SET_SELECTED_CAT_SUCCESS';
export const SET_SELECTED_CAT_FAILURE = 'SET_SELECTED_CAT_FAILURE';
export const ON_BACK_TO_CATS = 'ON_BACK_TO_CATS';
